### ISSUE TITLE
scikit

### ISSUE THREAD

**Issue by arjunroychowdhury** [blindmotion/docs#1]
Hi, is the scikit train/prediction usable? The document has a TBD on it so not sure what steps to follow - I'll explore, but if you can give some starting guidance it will be faster. I'd prefer to use scikit compared to octave. Thanks.

**Comment by arjunroychowdhury** [comment]
wrong repo, will add to detector

**Comment by lamerman** [comment]
I don't remember results of each of them... It was too long ago. :( The
octave one works, but using scikit is much simpler. Try to start with it.
